### ISSUE TITLE
Y Range off set not updating

### ISSUE THREAD

**Issue by Dr-Banana-PhD** [Qendolin/better-clouds#238]
## Describe the bug
Don't know if it is a bug but can't seem to get it working. 
Adjusting the Y Range off set doesn't seem to do anything. 

## To Reproduce
> Steps to reproduce the behavior

1.  Tried on two different versions. 
2.  Adjusted cloud settings in Sodium

### System Environment
- GPU: AMD Radeon RX 5700 XT
- Mod Version: 1.10.2+1.21.8-fabric-a, 1.10.3+1.21.8-fabric-a
- OS: Windows 11

*Optional*
- Other Mods: Sodium, sodium extra, R's Sodium options, Lithium, C2M, Chunky, LDynamic Lights, puzzle, iris, bobby, Distant Horizons, Mod Menu, Visuality, Placerholder API, Flashback, EMF, ETF, Camera Utils, Better F3 Continuity, Xaeros World Map, YetAConfiLab

**Comment by Qendolin** [comment]
Confirmed, will be fixed in the next release

**Comment by Qendolin** [comment]
This should be fixed now

**Comment by Dr-Banana-PhD** [comment]
For 1.10.3+1.21.8-fabric-a? I'm in 1.21.8 and haven't seen a change yet in this version

**Comment by autumnly24** [comment]
Would it be possible to backport this fix at all? This is currently broken on 1.20.1 too

**Comment by Qendolin** [comment]
It should be fixed for all versions :/
I guess something went wrong. I'll reopen and look at it someday.

**Comment by dojofemy** [comment]
yOffset doesn't work at all in 1.21.11 - seems bugged, nothing happens when I tweak it.

**Comment by orangishcat** [comment]
Fixed in the next update for 26.1, will release soon.

**Comment by autumnly24** [comment]
This is still broken on 1.20.1, no update was ever released to patch it

**Comment by orangishcat** [comment]
Yeah my dev environment is kinda broken right now. The game just refuses to launch. Hopefully I will be able to fix at some point
